---
title: "Reproducible Document"
author: "rostools" 
format: html
editor: visual
---

```{r setup}
#| message: false
#| warning: false
library(tidyverse)

post_meal_data <- read.csv2(here::here("data/post-meal-insulin.csv"))
```

### Header2

- Day
- Night

## About me

1. Rikke Hjortebjerg
2. University of Southern Denmark 
3. **Denmark** 

## **Simple code**

```{r}
```
## Showing the data
```{r}
post_meal_data

glimpse(post_meal_data)
```
ggplot(post_meal_data, aes(x = BMI)) + geom_histogram()

## Plot one continous variable

```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```


## Exercise: discrete plots
```{r}
#| fig-cap: "Glycaemia"
#| label: fig-glycaemia
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

See @fig-glycaemia above for a cool plot!


## Plotting two discrete variables

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar()
```

```{r}
ggplot(post_meal_data, aes(x = Group, fill = as.character(glykemi))) +
  geom_bar(position = position_dodge())
```


## Side by side plots

```{r}
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
```


```{r}
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```

## Side-by-side plots

```{r fig-bmi-glycemia}
#| fig-cap: "BMI and glycemia, side by side."
#| fig-subcap:
#|   - "Distribution of BMI."
#|   - "Number of those with glycemia."
#| layout-ncol: 2
ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
ggplot(post_meal_data, aes(x = glykemi)) +
  geom_bar()
```


## Plotting two continuous variables

```{r}
#| fig-cap: "Scatterplot of BMI and the area under the curve for glucose."
#| label: fig-bmi-auc-pg
ggplot(post_meal_data, aes(x = BMI, y = auc_pg)) +
  geom_point() +
  geom_smooth()
```
